#include "table.h"
#include "commands.h"

command cmd_tab[0x2d] = {
	/*0x00*/	{"add", ADD, 0, add_command },
	/*0x01*/	{"and", AND, 0, and_command },
	/*0x02*/	{"call", CALL, 1, call_command },
	/*0x03*/	{"cmp", CMP, 0, cmp_command },
	/*0x04*/	{"dec", DEC, 1, dec_command },
	/*0x05*/	{"div", DIV, 0, div_command },
	/*0x06*/	{"dup", DUP, 0, dup_command },
	/*0x07*/	{"hlt", HLT, 0, hlt_command },
	/*0x08*/	{"idiv", IDIV, 0, idiv_command },
	/*0x09*/	{"imul", IMUL, 0, imul_command },
	/*0x0a*/	{"inc", INC, 1, inc_command },
	/*0x0b*/	{"int", INT, 0, int_command },
	/*0x0c*/	{"into", INTO, 0, into_command },
	/*0x0d*/	{"ja", JA, 0, ja_command },
	/*0x0e*/	{"jc", JC, 1, jc_command },
	/*0x0f*/	{"jmp", JMP, 1, jmp_command },
	/*0x10*/	{"jnz", JNZ, 0, jnz_command },
	/*0x11*/	{"jz", JZ, 0, jz_command },
	/*0x12*/	{"lea", LEA, 0, lea_command },
	/*0x13*/	{"load", LOAD, 1, load_command },
	/*0x14*/	{"loop", LOOP, 0, loop_command },
	/*0x15*/	{"loope", LOOPE, 0, loope_command },
	/*0x16*/	{"loopne", LOOPNE, 0, loopne_command },
	/*0x17*/	{"mul", MUL, 0, mul_command },
	/*0x18*/	{"neg", NEG, 0, neg_command },
	/*0x19*/	{"nop", NOP, 0, nop_command },
	/*0x1a*/	{"not", NOT, 0, not_command },
	/*0x1b*/	{"or", OR, 0, or_command },
	/*0x1c*/	{"over", OVER, 0, over_command },
	/*0x1d*/	{"pop", POP, 0, pop_command },
	/*0x1e*/	{"prt", PRT, 0, prt_command },
	/*0x1f*/	{"push", PUSH, 1, push_command },
	/*0x20*/	{"ret", RET, 0, ret_command },
	/*0x21*/	{"rol", ROL, 0, rol_command },
	/*0x22*/	{"ror", ROR, 0, ror_command },
	/*0x23*/	{"sahf", SAHF, 0, sahf_command },
	/*0x24*/	{"sal", SAL, 0, sal_command },
	/*0x25*/	{"sar", SAR, 0, sar_command },
	/*0x26*/	{"shl", SHL, 0, shl_command },
	/*0x27*/	{"shr", SHR, 0, shr_command },
	/*0x28*/	{"sub", SUB, 0, sub_command },
	/*0x29*/	{"superpupercommand", SUPERPUPERCOMMAND, 0, superpupercommand_command },
	/*0x2a*/	{"test", TEST, 0, test_command },
	/*0x2b*/	{"xchg", XCHG, 0, xchg_command },
	/*0x2c*/	{"xor", XOR, 0, xor_command },
};